version: "3.9"

services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    restart: unless-stopped
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=web
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.le.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
      - --log.level=DEBUG
      - --accesslog=true
      - --accesslog.filepath=/logs/access.log
    ports:
      - "5677:5677"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/letsencrypt
      - ./traefik/logs:/logs
    networks: [web]

  postgres:
    image: postgres:16-alpine
    container_name: n8n-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks: [web]

  n8n:  
    build:
      context: .
      dockerfile: Dockerfile/Dockerfile
    ports:
      - "5678:5678"
    image: n8nio/n8n:2.4.6
    container_name: n8n
    restart: unless-stopped
    environment:
      N8N_HOST: ${N8N_HOST}
      N8N_PORT: ${N8N_PORT}
      N8N_PROTOCOL: ${N8N_PROTOCOL}
      WEBHOOK_URL: ${WEBHOOK_URL}
      N8N_EDITOR_BASE_URL: ${N8N_EDITOR_BASE_URL}
      GENERIC_TIMEZONE: ${GENERIC_TIMEZONE}
      N8N_SECURE_COOKIE: ${N8N_SECURE_COOKIE}

      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: ${POSTGRES_DB}
      DB_POSTGRESDB_USER: ${POSTGRES_USER}
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}

      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      N8N_BASIC_AUTH_ACTIVE: ${N8N_BASIC_AUTH_ACTIVE}
      N8N_BASIC_AUTH_USER: ${N8N_BASIC_AUTH_USER}
      N8N_BASIC_AUTH_PASSWORD: ${N8N_BASIC_AUTH_PASSWORD}
      NODES_EXCLUDE: "[]" # enable the ExecuteCommand and LocalFileTrigger(disabled dor security reasons)

      N8N_LDAP_ENABLED: "false"

      N8N_RESTRICT_FILE_ACCESS_TO: /files
      N8N_ENABLE_FS_ACCESS: "true"
      N8N_PROXY_HOPS: "2"


    user: "0:0"
    volumes:
      - ./n8n-data:/home/node/.n8n
      - ./n8n-data/tmp/audio:/files/audio
      - ./n8n-data/tmp/video:/files/video
      - ./n8n-data/tmp/final:/files/final
      - ./n8n-data/tmp/avatar:/files/avatar

    networks:
      - stack_net
      - web
      - tunnel

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel run n8n
    volumes:
      - ./cloudflared:/etc/cloudflared
    depends_on:
      - n8n
    networks:
      - tunnel

  piper-api:
    build: ./piper-api
    ports:
      - "8000:8000"
    volumes:
      - ./voices:/voices:ro
    environment:
      - PIPER_MODEL=/voices/ru_RU-irina-medium.onnx
      - PIPER_CONFIG=/voices/ru_RU-irina-medium.onnx.json
    networks:
      - stack_net
      - web

networks:
  stack_net:
    external: true
  tunnel:
    driver: bridge
  web:
    name: web